version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - EMAIL_HOST_USER=your_email@gmail.com
      - EMAIL_HOST_PASSWORD=your_password
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: price_alert
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data: